#!/usr/bin/env python3
"""
Локальный сервер для Инвест Dashboard.
- Отдаёт dashboard/index.html
- GET /api/prices → получает актуальные котировки с Yahoo Finance,
  сохраняет в data/prices.json и обновляет portfolio.json
Запуск: python scripts/server.py          (порт 8080)
        python scripts/server.py --port 9000
"""

import json
import os
import sys
import argparse
from datetime import datetime, timezone
from http.server import HTTPServer, SimpleHTTPRequestHandler
from urllib.request import urlopen, Request
from urllib.error import URLError

# ── Пути ──────────────────────────────────────────────────────
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PRICES_PATH = os.path.join(ROOT, "data", "prices.json")
PRICES_JS_PATH = os.path.join(ROOT, "data", "prices.js")
PORTFOLIO_PATH = os.path.join(ROOT, "data", "portfolio.json")
DASHBOARD_PATH = os.path.join(ROOT, "dashboard", "index.html")

# Yahoo Finance тикеры (LSE, в USD)
TICKER_MAP = {
    "SWRD": "SWRD.L",
    "EIMI": "EIMI.L",
    "USSC": "USSC.L",
}


def fetch_yahoo_price(symbol: str) -> float | None:
    """Получает текущую цену через Yahoo Finance v8 API."""
    url = f"https://query1.finance.yahoo.com/v8/finance/chart/{symbol}?interval=1d&range=1d"
    headers = {"User-Agent": "Mozilla/5.0"}
    req = Request(url, headers=headers)
    try:
        with urlopen(req, timeout=10) as resp:
            data = json.loads(resp.read().decode())
        meta = data["chart"]["result"][0]["meta"]
        # regularMarketPrice — последняя цена рынка
        return round(meta["regularMarketPrice"], 4)
    except Exception as e:
        print(f"  ⚠️  Ошибка при получении {symbol}: {e}")
        return None


def fetch_all_prices() -> dict:
    """Получает цены для всех ETF. Возвращает dict {ETF: price}."""
    prices = {}
    for etf, yahoo_ticker in TICKER_MAP.items():
        print(f"  Запрашиваю {yahoo_ticker}...", end=" ")
        price = fetch_yahoo_price(yahoo_ticker)
        if price is not None:
            prices[etf] = price
            print(f"${price}")
        else:
            print("не удалось")
    return prices


def save_prices(prices: dict) -> dict:
    """Сохраняет цены в prices.json и обновляет portfolio.json."""
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    # 1) prices.json
    prices_data = {**prices, "as_of": now, "source": "yahoo_finance"}
    with open(PRICES_PATH, "w") as f:
        json.dump(prices_data, f, indent=2, ensure_ascii=False)
    print(f"  ✅ prices.json обновлён ({now})")

    # 2) prices.js — для работы при открытии HTML как файла (file://)
    js_content = f"// Auto-generated by server.py — не редактировать вручную\nwindow.__LIVE_PRICES__ = {json.dumps(prices_data, ensure_ascii=False)};\n"
    with open(PRICES_JS_PATH, "w") as f:
        f.write(js_content)
    print(f"  ✅ prices.js обновлён")

    # 3) portfolio.json — обновляем блок "prices"
    try:
        with open(PORTFOLIO_PATH, "r") as f:
            portfolio = json.load(f)
        for etf, price in prices.items():
            portfolio["prices"][etf] = price
        portfolio["prices"]["as_of"] = now[:10]  # дата без времени
        with open(PORTFOLIO_PATH, "w") as f:
            json.dump(portfolio, f, indent=2, ensure_ascii=False)
        print(f"  ✅ portfolio.json обновлён")
    except Exception as e:
        print(f"  ⚠️  Не удалось обновить portfolio.json: {e}")

    return prices_data


# ── HTTP Server ────────────────────────────────────────────────
class DashboardHandler(SimpleHTTPRequestHandler):
    def do_GET(self):
        if self.path == "/" or self.path == "/index.html":
            self._serve_file(DASHBOARD_PATH, "text/html")
        elif self.path == "/api/prices":
            self._handle_fetch_prices()
        elif self.path == "/api/prices/current":
            self._serve_file(PRICES_PATH, "application/json")
        else:
            # Пробуем отдать статику из ROOT
            self.directory = ROOT
            super().do_GET()

    def _serve_file(self, path, content_type):
        try:
            with open(path, "rb") as f:
                content = f.read()
            self.send_response(200)
            self.send_header("Content-Type", f"{content_type}; charset=utf-8")
            self.send_header("Content-Length", str(len(content)))
            self.send_header("Access-Control-Allow-Origin", "*")
            self.end_headers()
            self.wfile.write(content)
        except FileNotFoundError:
            self.send_error(404)

    def _handle_fetch_prices(self):
        """GET /api/prices — запрашивает Yahoo Finance и возвращает JSON."""
        print("\n📡 Запрос актуальных котировок...")
        prices = fetch_all_prices()

        if not prices:
            self._json_response(400, {"error": "Не удалось получить котировки"})
            return

        saved = save_prices(prices)
        self._json_response(200, saved)

    def _json_response(self, code, data):
        body = json.dumps(data, ensure_ascii=False).encode("utf-8")
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Access-Control-Allow-Origin", "*")
        self.end_headers()
        self.wfile.write(body)

    def log_message(self, format, *args):
        # Тише логируем
        if "/api/" in (args[0] if args else ""):
            super().log_message(format, *args)


def main():
    parser = argparse.ArgumentParser(description="Инвест Dashboard Server")
    parser.add_argument("--port", type=int, default=8080, help="Порт (по умолчанию 8080)")
    args = parser.parse_args()

    server = HTTPServer(("0.0.0.0", args.port), DashboardHandler)
    print(f"\n🚀 Dashboard запущен: http://localhost:{args.port}")
    print(f"   Нажми кнопку «Обновить цены» в дашборде или открой:")
    print(f"   http://localhost:{args.port}/api/prices\n")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\n👋 Сервер остановлен")
        server.server_close()


if __name__ == "__main__":
    main()
